import {
  SEARCH_START,
  SEARCH_SUCCESS,
  SEARCH_FAIL,
  SEARCH_SUGGEST,
  SEARCH_SET_ACTIVE,
  SEARCH_SET_SEARCHQUERY,
  SEARCH_GO_HOME,
  SEARCH_UPDATE_HISTORY,
  SEARCH_LOAD_MORE_SUCCESS,
  SEARCH_LOAD_MORE_FAIL,
  SEARCH_LOAD_MORE_START
} from "./types";

export const searchRecentKey = "@auth:searchRecent";
